# Pre-Commit CI Config
ci:
  autoupdate_schedule: monthly
  skip: [pretty-format-java, pretty-format-kotlin]

# We should never format the copied Calcite files, in order to avoid massive diffs when Calcite is updated.
# See https://bodo.atlassian.net/wiki/spaces/B/pages/1415970823/Bodo+s+Calcite+Fork#Managing-the-Fork
# Also exclude vendored duckdb code
exclude: ^BodoSQL/calcite_sql/bodosql-calcite-application/src/main/java/org/apache/calcite/|^BodoSQL/calcite_sql/bodosql-calcite-application/src/test/resources|^bodo/pandas/vendor/
repos:
  # Basics
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: debug-statements
        exclude: bodo-platform-image/ansible/roles/ipython/files/load_bodo_platform_extensions_magics.py
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
  # Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
  # Cython
  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.19.0
    hooks:
      - id: cython-lint
        args: [--no-pycodestyle]  # Because it doesn't autofix, it would be too annoying
      - id: double-quote-cython-strings
  # Java and Kotlin
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.16.0
    hooks:
      - id: pretty-format-java
        args: ["--autofix", "--google-java-formatter-version", "1.24.0"]
      - id: pretty-format-kotlin
        args: ["--autofix"]
  # C++
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.8
    hooks:
      - id: clang-format
        types_or: [c++]
        exclude: |
          (?x)^(bodo/libs/vendored/.*)$
  # GitHub Actions
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint

