name: base
channels:
  - conda-forge
  - bodo.ai
dependencies:
  - python=3.14
  - bodo
  - bodosql
  - bodo-iceberg-connector
  - jupyterlab=3
  - setuptools
  # To test and run notebooks
  - nbconvert
