CONDA_BUILD_SYSROOT:
  - /opt/MacOSX11.0.sdk        # [osx]

MACOSX_DEPLOYMENT_TARGET:
  - 11.0

python:
  - 3.8
  - 3.9

numpy:
  - 1.19

target_platform:
  - osx-arm64

SDKROOT:
  - /opt

c_compiler_version:
  - 12.0.1
cxx_compiler_version:
  - 12.0.1
