# Project information
site_name: Bodo Developer Documentation
site_url: https://docs.bodo.ai/
site_author: Bodo Team
site_description: >-
  Bodo offers a new type of just-in-time compiler with Supercomputing-style performance and the simplicity of using native Python.

# Copyright
copyright: Copyright &copy; 2019 - 2022 Bodo, Inc.

# Configuration
theme:
  name: material
  custom_dir: overrides
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - search.highlight
    - search.suggest
    - toc.follow
    - navigation.path
    - content.tooltips


  palette:
    - media: '(prefers-color-scheme: light)'
      primary: bodo-light
      accent: bodo-green
    - media: '(prefers-color-scheme: dark)'
      primary: bodo-light
      accent: bodo-green
  font:
    text: Archivo
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/bodo-logo.png

# Plugins
plugins:
  - search
  - autorefs
  - awesome-pages
  - meta-descriptions
  - tags
#      tags_file: tags.md


extra_css:
  - stylesheets/bodo.css

# Customization
extra:
  generator: false
  status:
    new: Recently added
  analytics:
      provider: google
      property: G-W019JWTQ1N
      feedback:
        title: Was this page helpful?
        ratings:
          - icon: material/emoticon-happy-outline
            name: This page was helpful
            data: 1
            note: >-
              Thanks for your feedback!
          - icon: material/emoticon-sad-outline
            name: This page could be improved
            data: 0
            note: >-
              Thanks for your feedback! Help us improve this page by
              filing an <a href="https://github.com/Bodo-inc/Feedback/issues/new" target=_blank>issue</a>.

  version:
    provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/bodocommunity/shared_invite/zt-qwdc8fad-6rZ8a1RmkkJ6eOX1X__knA
    - icon: fontawesome/brands/discourse
      link: https://discourse.bodo.ai 
    - icon: fontawesome/brands/github
      link: https://github.com/Bodo-Inc/Feedback
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bodo_ai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/19205698

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - grid_tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - quick_start/index.md
    - Quick Start (Platform): quick_start/quick_start_platform.md
    - Developer's Quick Start Guide: quick_start/dev_guide.md
  - API Reference:
      - api_docs/index.md
      - Bodo Parallel API Reference: api_docs/bodo_parallel_apis.md
      - Python Reference:
        - api_docs/python/index.md
        - Pandas:
            - api_docs/pandas/index.md
            - General Functions: api_docs/pandas/general.md
            - DataFrame: api_docs/pandas/dataframe.md
            - Groupby : api_docs/pandas/groupby.md
            - Series : api_docs/pandas/series.md
            - Window : api_docs/pandas/window.md
            - DateOffsets: api_docs/pandas/dateoffsets.md
            - Input/Output: api_docs/pandas/io.md
            - Index Objects: api_docs/pandas/indexapi.md
            - TimeDelta : api_docs/pandas/timedelta.md
            - Timestamp : api_docs/pandas/timestamp.md
        - Numpy: api_docs/numpy.md
        - User Defined Functions (UDFs): api_docs/udfs.md
        - Machine Learning:
            - api_docs/ml/index.md
            - Scikit Learn:
                - api_docs/ml/sklearn/index.md
                - sklearn.cluster : api_docs/ml/sklearn/cluster.md
                - sklearn.ensemble: api_docs/ml/sklearn/ensemble.md
                - sklearn.feature_extraction : api_docs/ml/sklearn/feature_extraction.md
                - sklearn.linear_model: api_docs/ml/sklearn/linear_model.md
                - sklearn.metrics: api_docs/ml/sklearn/metrics.md
                - sklearn.model_selection: api_docs/ml/sklearn/model_selection.md
                - sklearn.naive_bayes: api_docs/ml/sklearn/naive_bayes.md
                - sklearn.preprocessing: api_docs/ml/sklearn/preprocessing.md
                - sklearn.svm: api_docs/ml/sklearn/svm.md
      - BodoSQL Reference:
        - API: api_docs/BodoSQL.md
        - Errors: api_docs/bodosqlerrors.md
#      this following file is generated using a symlink. The latest version of bodo platform repo is
#      required to generate this file.
      - Bodo Platform SDK Reference: integrating_bodo/platform_sdk.md

  - Guides:
      - integrating_bodo/index.md
      - Using native SQL with Catalogs: integrating_bodo/database_catalog.md
      - Installation and Setup Guides:
          - installation_and_setup/index.md
          - Bodo Platform:
            - Bodo Platform Basics: installation_and_setup/bodo_platform.md
            - Bodo Platform on AWS: installation_and_setup/bodo_platform_aws.md
            - Bodo Platform on Azure: installation_and_setup/bodo_platform_azure.md
            - Bodo Platform SDK: installation_and_setup/platform_sdk.md
          - Bodo On-Prem:
            - Installing Bodo Community Edition: installation_and_setup/install.md
            - Configuring Bodo Enterprise Edition: installation_and_setup/enterprise.md
            - Interactive Bodo Cluster Setup using IPyParallel: installation_and_setup/ipyparallel.md
            - Recommended MPI Settings: installation_and_setup/recommended_mpi_settings.md
            - Recommended Cluster Configuration: installation_and_setup/recommended_cluster_config.md
      - Understanding Parallelism with Bodo:
          - Basics of Bodo Parallelism: bodo_parallelism/bodo_parallelism_basics.md
          - Advanced Parallelism Topics: bodo_parallelism/advanced.md
          - Typing Considerations: bodo_parallelism/typing_considerations.md
          - Unsupported Programs: bodo_parallelism/not_supported.md
      - Scalable Data I/O with Bodo: file_io.md
      - Running jobs on the Bodo Platform: integrating_bodo/bodo-jobs.md
      - Using Regular Python inside Bodo (Object Mode): objmode.md
      - Measuring Performance: performance/performance.md
      - Caching: performance/caching.md
      - Inlining: performance/inlining.md
      - Bodo Errors: diagnostics_and_troubleshooting/Bodoerrors.md
      - Compilation Tips: diagnostics_and_troubleshooting/compilation.md
      - Verbose Mode: diagnostics_and_troubleshooting/verbose_mode.md
      - Deploying Bodo with Kubernetes: integrating_bodo/kubernetes.md
  - Release Notes:
      - release_notes/index.md
