name: Azure packer cleanup

on:
  schedule:
      # Run everyday to ensure we delete stale resource groups
      - cron:  '00 00 * * *'
  workflow_dispatch:
    inputs:
      dryrun:
        description: dryrun. true by default, i.e. only finds the Packer resource groups that would be removed but doesn't delete them from Azure.
        required: false
        default: 'true'

jobs:

  find_and_delete_resource_groups:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
    
      - name: Configure Azure Credentials
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          set -eo pipefail
          python -m pip install requests
          python -m pip install adal==1.2
          python -m pip install azure.identity==1.10
          python -m pip install azure.mgmt.resource==21.1
        
      - name: Find and delete packer resource groups
        env:
          DRYRUN: ${{ github.event.inputs.dryrun }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          set -eo pipefail
          cd bodo-platform-image
          DELETE_FLAG="--delete"
          if [[ "$DRYRUN" == "true" ]]; then
            # default is delete for cron schedule
            DELETE_FLAG="--no-delete"
          fi
          python azure_packer_cleanup.py --output resource_groups_to_remove.json $DELETE_FLAG

      - name: Upload Resource Group Details
        uses: actions/upload-artifact@v4
        with:
          name: removed-resource-groups
          path: bodo-platform-image/resource_groups_to_remove.json
